queries:
  - exclude: cpp/fixme-comment
  - exclude: cpp/empty-block
# symver attribute detection cannot be used, disable it for lgtm
extraction:
  cpp:
    configure:
      command:
      - "./autogen.sh"
      - "./configure --enable-external-tokens --enable-ssh-token"
      - "echo \"#undef HAVE_ATTRIBUTE_SYMVER\" >> config.h"
