---
include:
  - https://salsa.debian.org/salsa-ci-team/pipeline/raw/master/recipes/debian.yml

variables:
  RELEASE: 'bookworm'
  # Skip all DEP-8 tests except 'cryptroot-lvm': each 'cryptroot-*' test
  # takes 20-30min on Salsa CI runners as they don't support KVM acceleration
  # cf. https://salsa.debian.org/salsa-ci-team/pipeline/-/issues/266 ,
  # and other tests are skipped anyway since they require machine-level
  # isolation which the runners currently don't provide.
  # Running 'cryptroot-lvm' and 'cryptroot-legacy' only is significantly
  # better than disabling the autopkgtest job altogether.
  SALSA_CI_AUTOPKGTEST_ARGS: '--test-name=cryptroot-lvm --test-name=cryptroot-legacy'

# Run reprotest job under 'nocheck' build profile.  The job runs with
# root privileges, which trigger extra tests within the upstream test
# suite.  Some of these extra tests want to interact with the kernel,
# load modules, and create/remove loop devices, which is beyond the
# scope of the reprotest job.
reprotest:
  extends: .test-reprotest
  variables:
    DEB_BUILD_OPTIONS: nocheck

# Add a deploy stage for pages
stages:
  - provisioning
  - build
  - publish
  - test
  # would be better if we could extend the list rather than override it
  - deploy

pages:
  image: debian:11
  script:
    - apt-get update
    - apt-get -y install pandoc
    - mkdir public
    # install CSS file
    - install -m0644 debian/doc/pandoc/pandoc.css public/pandoc.css
    # install index.html
    - ${PANDOC} -T "Debian Cryptsetup docs" -o public/index.html
          debian/doc/pandoc/index.md
    # install README.*.html files
    - for readme in Debian debug gnupg gnupg-sc initramfs keyctl opensc; do
          ${PANDOC} --toc -T "Debian Cryptsetup docs"
          -o public/README.$readme.html debian/README.$readme; done
    - ${PANDOC} -pNo public/encrypted-boot.html
          debian/doc/pandoc/encrypted-boot.md
  stage: deploy
  artifacts:
    paths:
      - public
  only:
    # only run on debian/latest branch
    refs:
      - debian/latest
    # only run when commit is tagged (to install docs on package releases only)
    #variables:
    #  - $CI_COMMIT_TAG
  variables:
    PANDOC: 'pandoc -s -c pandoc.css -f markdown+smart -t html'
